#pragma once
#include <algorithm>
#include <iostream>
#include <numeric>
#include <string>
#include <utility>
#include <vector>
#include <set>
#include <map>
#include <list>
#include <cctype>
#include <array>
#include <deque>
#include <iomanip>

using std::cin;
using std::cout;
using std::endl;
using std::vector;
using std::string;

void stl_case_1();
void stl_case_2();
void stl_case_3();
void stl_case_4();
void stl_case_5();
void stl_case_6();
void stl_case_7();
void stl_case_8();
void stl_case_9();
void stl_case_10();
void stl_case_11();
void section_20_challenge_1();
