#pragma once

void letter_grade_selection();
void enum_direction_example();
void conditional_operator_case_1();
void conditional_operator_case_2();
void for_loop_case_1();
void range_base_for_loop_case_1();
void range_base_for_loop_case_2();
void range_base_for_loop_case_3();
void range_base_for_loop_case_4();
void while_loop_case_1();
void while_loop_case_2();
void do_while_loop_case_1();
void do_while_loop_case_2();
void nested_loops_case_1();
void nested_loops_case_2();
void nested_loops_case_3();
void section_9_challenge();
