#pragma once

void pointers_case_1();
void pointers_case_2();
void pointers_case_3();
void pointers_case_4();
void pointers_case_5();
void dynanmic_memory_allocation_case_1();
void dynanmic_memory_allocation_case_2();
void relationship_between_arrays_pointers_case_1();
void relationship_between_arrays_pointers_case_2();
void relationship_between_arrays_pointers_case_3();
void relationship_between_arrays_pointers_case_4();
void pointer_arithmetic_case_1();
void pointer_arithmetic_case_2();
void pointer_arithmetic_case_3();
void pass_pointers_to_functions_case_1();
void pass_pointers_to_functions_case_2();
void returning_pointers_case_1();
void returning_pointers_case_2();
void section_12_exercise_33();
void section_12_exercise_34();
