#pragma once

#include ".\include\Sections\Section_6\section_6.h"
#include ".\include\Sections\Section_7\section_7.h"
#include ".\include\Sections\Section_8\section_8.h"
#include ".\include\Sections\Section_9\section_9.h"
#include ".\include\Sections\Section_10\section_10.h"
#include ".\include\Sections\Section_11\section_11.h"
#include ".\include\Sections\Section_12\section_12.h"
#include ".\include\Sections\Section_13\section_13.h"
#include ".\include\Sections\Section_14\section_14.h"
#include ".\include\Sections\Section_15\section_15.h"
#include ".\include\Sections\Section_16\section_16.h"
#include ".\include\Sections\Section_17\section_17.h"
#include ".\include\Sections\Section_18\section_18.h"
#include ".\include\Sections\Section_19\section_19.h"
